platform :ios, '13.0'

target 'Example' do 
  use_frameworks!

  # Pods for Example
  pod 'TealiumPrismFirebase', :path => '../'
  pod 'tealium-prism/Core', :path => '../../tealium-swift-v3/'
  pod 'tealium-prism/Lifecycle', :path => '../../tealium-swift-v3/'
end